#!/bin/bash

echo "starting installer"

# source installation vars for this systems
source "$(pwd)/install/scripts/installer_vars.sh" &&

# run installs for all unix envs
$UNIX_SYS_DIR/devtools &&

# run system-specific installs
if [ "$SYSTEM_TYPE" = "Linux" ]; then
    bash "$INSTALLATION_ROOT/systems/linux";
elif [ "$SYSTEM_TYPE" = "Mac" ]; then
    $MACOS_SYS_DIR/devtools;
    $MACOS_SYS_DIR/utils;
else
    echo "WARNING: unsupported system type, neither mac nor linux, skipping Azure CLI installation."
fi