#!/bin/bash
echo "installing shared unix system tools ..."

# run system-specific homebrew installation
if [ "$(should_install brew)" == "true" ]; then
    if [ "$SYSTEM_TYPE" = "Linux" ]; then
        bash $INSTALLER_DIR/utils/install-homebrew-linux.sh
    elif [ "$SYSTEM_TYPE" = "Mac" ]; then
        bash $INSTALLER_DIR/utils/install-homebrew-mac.sh
    else
        echo "WARNING: unsupported system type, neither mac nor linux, skipping Azure CLI installation."
    fi
else 
    echo "homebrew already installed ✅"
fi

tryInstall "docker"
tryInstall "ibmcloud"
tryInstall "az"
tryInstall "node"
tryInstall "python"