#!/bin/bash

echo "checking for unix env developer tools ..."

# source vars
source $INSTALLER_DIR/installer_vars.sh

echo "$(should_install curl)"

# determine if Curl should be installed
if [ "$(should_install curl)" == "true" ]; then
    sh $INSTALLER_DIR/utils/install-curl.sh;
else 
    echo "Curl already installed ✅"
fi

# determine if Homebrew should be installed
if [ "$(should_install brew)" == "true" ]; then
    sh $INSTALLER_DIR/utils/install-homebrew.sh;
else 
    echo "Homebrew already installed ✅"
fi

# determine if Bash should be installed
if [ "$(should_install sshpass)" == "true" ]; then
    sh $INSTALLER_DIR/utils/install-sshpass.sh;
else 
    echo "sshpass already installed ✅"
fi

# determine if IBM Cloud CLI should be installed
if [ "$(should_install ibmcloud)" == "true" ]; then
    sh $INSTALLER_DIR/utils/install-ibmcloud-cli.sh;
else 
    echo "IBM Cloud CLI already installed ✅"
fi

# determine if Azure CLI should be installed
if [ "$(should_install az)" == "true" ]; then
    sh $INSTALLER_DIR/utils/install-azure-cli.sh;
else 
    echo "Microsoft Azure CLI already installed ✅"
fi
